---
title: "Introducción proyecto"
format: html
editor: visual
author: "Javiera Rojas"
lang: es
theme: litera
---

Podemos considerar al mundo como un rompecabezas donde las piezas están compuestas por los continentes y que además cada uno de ellos poseen otras piezas que son los países, pues este rompecabezas no solo se puede decir que las piezas encajan a la perfección, sino que se puede ir más allá, es decir que económicamente y funcionalmente trabajan en conjunto, tanto por los tratados que existen entre cada uno de ellos, las relaciones internacionales, entre otras razones. Hoy algunos países son mucho más importantes que otros por su dimensión territorial, pero más imponente por su poder económico, poder político y sus avances sobre la sociedad o habitantes. Una pieza del mundo que influye en esto o cuenta con estas características es el continente asiático, que cuenta con avances tecnológicos y donde la sociedad se ve influenciada con gran poder en esto, pero sin perder sus raíces antiguas: uno de los países que destaca corresponde a Corea del Sur, que luego de su separación de Corea del Norte, la urbanización impactó fuertemente en su sociedad, sobre todo los más jóvenes, que desde regiones se movilizaban a la ciudad con tal de obtener mejores oportunidades. También es considerado como una gran potencia económica, con un gran indicador del valor de la vida (PIB) y por su densidad poblacional. 

Este último factor es considerado importante debido a que Corea del Sur se encuentra en el puesto 28 de 196 por la cantidad de habitantes que posee, es por esto que cabe destacar que la población fue influida por un hecho histórico que ocurrió en 1948 por lo que provocó mayor inmigración de personas, es decir, mayor cantidad de habitantes, trayendo luego de un tiempo mayores personas casadas, más nacimientos y, como hay un crecimiento de número de personas, se produce en algunos casos un aumento de muertes y otras características que trae el crecimiento de personas dentro de una densidad, pero ¿Qué ha pasado con la población en los últimos 20 años? ¿Han existido otros hechos que han provocado efectos en los nacimientos o muertes? ¿Los eventos dentro de un país influyen en la toma de decisiones como el casarse? Es por esto que en este proyecto se abordará el responder estas preguntas que nos ayudarán y es considerable para saber qué tendencia tendrán o si existe un evento tanto externo o interno del país que afecte en la vida de las personas dentro del desarrollo de este.

Es por esto que se analizará y se trabajará con una base de datos de Corea del Sur, que almacena los datos de los últimos 20 años de cómo ha evolucionado por ciudad algunos aspectos como el número de muertes, nacimientos, divorcios, entre otros aspectos, teniendo en consideración los eventos importantes que han ocurrido en este periodo de tiempo, dentro de este mismo país como mundialmente. Desde aquí se tratará de ver cómo algunos hechos históricos, tanto de tipo económico como relación entre países, afecta a la sociedad, tal como la toma de decisiones de sus vidas; lo que involucra el tener hijos, formalizar una relación, tasa de crecimiento o incluso el acabar con su vida, en el caso extremo.

El objetivo de este proyecto es el conocer cómo se comporta la sociedad dentro de un amplio período de tiempo y cómo ha evolucionado la demografía de este, enfocándonos en una potencia mundial como Corea. 

Este proyecto contará con distintas etapas para llegar a los resultados y conclusiones, donde en primera instancia se limpiará esta base de datos para no llegar a resultados con cierto sesgo por datos mal ingresados, para luego trabajar con ellos por medio de gráficos y tablas que se crearán para analizar las tendencias y progreso del número de aspectos y el número de muertes, nacimientos, etc. En tanto como país como en algunas ciudades importantes de este; y al mismo tiempo ver el contexto en que se encontraba el mundo y Corea, para finalmente concluir y descubrir si existe alguna tendencia con ciertos eventos que podrían no solo haber afectado a Corea, sino a otros países para estar alerta si es que sucede tal hecho o similar en el mundo y anticiparse, viendo así si es que este afecta negativamente.

\

